# TS definitions are to be interpreted by the agent node. The LTL core planner only uses the node names, connections, weights, and action names to build its automaton.
#
# Possible TS types:
#   3d_pose_region (3D pose [[x,y,z], [x,y,z,w]] with quaternion orientation)
#   2d_pose_region (2D pose [[x,y], phi] with euler angle orientation)
#   3d_point_region (3D point [x, y, z] without orientation)
#   2d_point_region (2D point [x, y] without orientation)
#   turtlebot_load

#state_dim: ["2d_pose_region", "turtlebot_load"]
state_dim: ["2d_pose_region", "DR_load"]
state_models:
  2d_pose_region:
    ts_type: "2d_pose_region"
    initial: "reception"
    nodes:
      reception:
        attr:
          type: "square"
          pose: [[4.5,1.5], [0]]
          length: 3.0
          hysteresis: 0.05
        connected_to:
          reception: "stay"
          corridor1: "goto_c1_from_rec"
      corridor1:
        attr:
          type: "square"
          pose: [[10,0.5], [0]]
          length: 2.0
          hysteresis: 0.05
        connected_to:
          corridor1: "stay"
          corridor2: "goto_c2_from_c1"
          reception: "goto_rec_from_c1"
      corridor2:
        attr:
          type: "square"
          pose: [ [16,0.62 ], [ 0 ] ]
          length: 2.0
          hysteresis: 0.05
        connected_to:
          corridor1: "goto_c1_from_c2"
          corridor2: "stay"
          corridor3: "goto_c3_from_c2"
      corridor3:
        attr:
          type: "square"
          pose: [[21.5,0.8], [0]]
          length: 2.0
          hysteresis: 0.05
        connected_to:
          corridor3: "stay"
          corridor2: "goto_c2_from_c3"
          corridor4: "goto_c4_from_c3"
      corridor4:
        attr:
          type: "square"
          pose: [[21.5,5.625], [0]]
          length: 1.0
          hysteresis: 0.05
        connected_to:
          corridor5: "goto_c5_from_c4"
          corridor4: "stay"
          corridor3: "goto_c3_from_c4"
          room1: "goto_r1_from_c4"
      corridor5:
        attr:
          type: "square"
          pose: [ [ 21.35,7.2 ], [ 0 ] ]
          length: 1.0
          hysteresis: 0.05
        connected_to:
          corridor5: "stay"
          corridor4: "goto_c4_from_c5"
          room1: "goto_r1_from_c5"
          room2: "goto_r2_from_c5"
      room1:
        attr:
          type: "square"
          pose: [[23.485,7.662], [0]]
          length: 1.5
          hysteresis: 0.05
        connected_to:
          room1: "stay"
#          room2: "goto_r2_from_r1"
          corridor4: "goto_c4_from_r1"
          corridor5: "goto_c5_from_r1"
      room2:
        attr:
          type: "square"
          pose: [[18.476,7.35], [0]]
          length: 1.5
          hysteresis: 0.05
        connected_to:
#          room1: "goto_r1_from_r2"
          room2: "stay"
#          corridor4: "goto_c4_from_r2"
          corridor5: "goto_c5_from_r2"

  DR_load:
    ts_type: "DR_load"
    initial: "standby"
    nodes:
      standby:
        connected_to:
          loaded: "pick"
      loaded:
        connected_to:
          standby: "drop"

actions:
  goto_rec_from_c1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: reception
      pose: [[3.5,1.5,0], [0,0,-0.707,0.707]]
  goto_c1_from_rec:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor1
      pose: [[10.0,0,0], [0,0,0,1]]
  goto_c1_from_c2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor1
      pose: [[10.0,1.3,0], [0,0,1,0]]
  goto_c2_from_c1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor2
      pose: [[16,0.15,0], [0,0,0,1]]
  goto_c2_from_c3:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor2
      pose: [[16,1.15,0], [0,0,1,0]]
  goto_c3_from_c2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor3
      pose: [[21.77,0.48,0], [0,0,0.707,0.707]]
  goto_c3_from_c4:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor3
      pose: [[21.3,1.28,0], [0,0,1,0]]
  goto_c4_from_c3:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor4
      pose: [[21.77,5.625,0], [0,0,-0.707,-0.707]]
  goto_c4_from_r1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor4
      pose: [[21.11,5.625,0], [0,0,-0.699,0.715]]
  goto_c4_from_r2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor4
      pose: [[21.11,5.625,0], [0,0,-0.699,0.715]]
  goto_c4_from_c5:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor4
      pose: [[21.11,5.625,0 ], [ 0,0,-0.699,0.715 ] ]
  goto_c5_from_c4:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor5
      pose: [ [ 21.75,7.0,0 ], [ 0,0,0.707,0.707 ] ]
  goto_c5_from_r1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor5
      pose: [ [ 21.75,7.4,0 ], [ 0,0,1,0 ] ]
  goto_c5_from_r2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: corridor5
      pose: [[21.05,7.38,0], [0,0,0,1]]
  goto_r1_from_c4:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: room1
      pose: [[23.485,7.662,0], [0,0,0.707,0.707]]
  goto_r1_from_r2:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: room1
      pose: [[23.485,7.662,0], [0,0,0.707,0.707]]
  goto_r1_from_c5:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: room1
      pose: [ [ 23.485,7.662,0 ], [ 0,0,0.707,0.707 ] ]
  goto_r2_from_c4:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: room2
      pose: [[18.476,7.35,0], [0,0,1,0]]
  goto_r2_from_r1:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: room2
      pose: [[18.476,7.35,0], [0,0,1,0]]
  goto_r2_from_c5:
    type: "move"
    weight: 10
    guard: "1"
    attr:
      region: room2
      pose: [ [ 18.476,7.35,0 ], [ 0,0,1,0 ] ]

  stay:
    type: "stay"
    guard: "1"
    weight: 0.01
  synchronized_transition:
    type: "stay"
    guard: "1"
    weight: 0
  pick:
    type: "pick"
    guard: "room2"
    weight: 10
  drop:
    type: "drop"
    guard: "1"
    weight: 10


